apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-cost-management
  title: Terraform Module: cost-management
  description: Azure infrastructure module for cost-management
  annotations:
    github.com/project-slug: logtailer/azure-automation-suite
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - azure
    - cost-management
spec:
  type: infrastructure
  lifecycle: production
  owner: platform-team
  system: azure-platform
