apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-networking
  title: Terraform Module: networking
  description: Azure infrastructure module for networking
  annotations:
    github.com/project-slug: logtailer/azure-automation-suite
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - azure
    - networking
spec:
  type: infrastructure
  lifecycle: production
  owner: platform-team
  system: azure-platform
