apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sreadonlyrootfilesystem
  annotations:
    description: Requires containers to use a read-only root filesystem.
spec:
  crd:
    spec:
      names:
        kind: K8sReadOnlyRootFilesystem
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sreadonlyrootfilesystem

        import future.keywords.if

        violation[{"msg": msg}] if {
          container := input.review.object.spec.containers[_]
          not container.securityContext.readOnlyRootFilesystem
          msg := sprintf("Container <%v> must use a read-only root filesystem", [container.name])
        }

        violation[{"msg": msg}] if {
          container := input.review.object.spec.containers[_]
          container.securityContext.readOnlyRootFilesystem == false
          msg := sprintf("Container <%v> must use a read-only root filesystem", [container.name])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sReadOnlyRootFilesystem
metadata:
  name: require-read-only-root-filesystem
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - istio-system
      - cert-manager
