apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-api-sa
  namespace: platform
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_CLIENT_ID"
    azure.workload.identity/tenant-id: "REPLACE_WITH_TENANT_ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-worker-sa
  namespace: platform
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_WORKER_CLIENT_ID"
    azure.workload.identity/tenant-id: "REPLACE_WITH_TENANT_ID"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: platform
  annotations:
    azure.workload.identity/client-id: "REPLACE_WITH_ESO_CLIENT_ID"
    azure.workload.identity/tenant-id: "REPLACE_WITH_TENANT_ID"
  labels:
    azure.workload.identity/use: "true"
