apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-traffic-manager
  title: Terraform Module: traffic-manager
  description: Azure infrastructure module for traffic-manager
  annotations:
    github.com/project-slug: logtailer/azure-automation-suite
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - azure
    - traffic-manager
spec:
  type: infrastructure
  lifecycle: production
  owner: platform-team
  system: azure-platform
